services:
    postgres:
        image: postgres:15
        container_name: dubpay-postgre-container
        restart: no
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: dubpay
        ports:
            - "5480:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
