services:
  postgres:
    image: postgres:15
    container_name: descobre-aqui-postgre-container
    restart: no
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: descobre-aqui
    ports:
      - '5460:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
